version: '2'
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpressmysql
    depends_on:
      - database
    restart: always
    links:
      - database
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_PASSWORD: password
      
  database:
    image: mysql:5.7.24
    container_name: mysqlwordpress
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - "./volumes/database:/var/lib/mysql"